name: Deploy Server

on: 
  push:
    branches:
    - master
    paths:
    - "src/*"
    - ".github/workflows/DeployServer.yml"

jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test workflow
        run: echo "YAY this workflow is running" 
      - name: Add github username
        run: git config --global user.name 'pradeep1412'
      - name: Add github email
        run: git config --global user.email 'ppradeepkumar1412@gmail.com'
      - name: add heroku remote
        run: git remote add heroku https://heroku:eb902efb-1160-49ae-b73f-2cf788777fb4@git.heroku.com/emr-1-api.git
      - name: push to heroku remote
        run: git push heroku master --force